### PR TITLE
Remove API key support

### PR DESCRIPTION
**Pull request by muradsater**

### CODE REVIEW

**Comment by haakonvt** [comment]
Lots of API key references in README.md

**Comment by haakonvt** [comment]
Also, is this even used anymore?

**Comment by muradsater** [comment]
> Lots of API key references in README.md

Where? Did you check the README.md in this branch

**Comment by muradsater** [comment]
> Also, is this even used anymore?

Yes, or is there an alternative?

**Comment by haakonvt** [comment]
> > Lots of API key references in README.md
> 
> Where? Did you check the README.md in this branch

Oops, my mistake, looked at the wrong one

**Review by dmivankov — APPROVED** [review]

**Pull request merged**
